services:
    violation_photo.form.type:
        class: AppBundle\Form\Type\ViolationFormType
        tags:
            - { name: form.type, alias: violation_photo_form }
    violation_video.form.type:
        class: AppBundle\Form\Type\ViolationVideoCreateType
        tags:
            - { name: form.type, alias: violation_video_form }